# Generated by npm run container:sync.
# Source of truth: package.json version + release/container-image.json.
export APP_PEARPASTE_IMAGE="ghcr.io/bigdestiny2/pearpaste:0.1.0"
export APP_PEARPASTE_WEB_PORT="3000"
export APP_PEARPASTE_UMBREL_PORT="9195"
