#!/usr/bin/env bash
# Paste — app icon build pipeline.
#
# Inputs (hand-authored, version-controlled):
#   ui/shared/assets/icon-src/icon-master.svg     — 1024×1024 full-bleed
#   ui/shared/assets/icon-src/icon-foreground.svg — Android adaptive foreground
#
# Outputs (regenerated by this script):
#   ui/shared/assets/icon-out/                    — all rasterized PNGs + .icns + .ico
#   mobile/pearpaste-expo/assets/images/icon.png  — iOS / cross-platform expo icon
#   mobile/pearpaste-expo/assets/images/adaptive-icon.png — Android foreground
#   mobile/pearpaste-expo/assets/images/favicon.png       — small web favicon
#   mobile/pearpaste-expo/assets/images/splash-icon.png   — Expo splash
#   assets/icon.png / icon.icns / icon.ico        — desktop (pear-electron)
#
# Requires:  rsvg-convert (brew install librsvg), iconutil (macOS), python3+PIL
#
# Re-run any time the SVG changes:
#     bash scripts/build-icons.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/ui/shared/assets/icon-src"
OUT="$ROOT/ui/shared/assets/icon-out"
MASTER="$SRC/icon-master.svg"
FG="$SRC/icon-foreground.svg"

command -v rsvg-convert >/dev/null || { echo "missing rsvg-convert (brew install librsvg)"; exit 1; }
command -v python3 >/dev/null      || { echo "missing python3"; exit 1; }
[[ -f "$MASTER" ]] || { echo "missing $MASTER"; exit 1; }
[[ -f "$FG" ]]     || { echo "missing $FG"; exit 1; }

mkdir -p "$OUT"
rm -f "$OUT"/*.png "$OUT"/*.icns "$OUT"/*.ico 2>/dev/null || true

# ---- 1. Master PNG ladder (used by iOS, Android, desktop) -----------------
SIZES=(16 20 24 29 32 40 48 50 57 58 60 64 72 76 80 87 96 100 114 120 128 144 152 167 180 192 256 384 512 1024)
for s in "${SIZES[@]}"; do
  rsvg-convert -w "$s" -h "$s" "$MASTER" -o "$OUT/icon-$s.png"
done
echo "✓ rasterized ${#SIZES[@]} master sizes (16…1024)"

# ---- 2. Android adaptive foreground ---------------------------------------
rsvg-convert -w 1024 -h 1024 "$FG" -o "$OUT/adaptive-icon-1024.png"
rsvg-convert -w 432  -h 432  "$FG" -o "$OUT/adaptive-icon-432.png"
echo "✓ rasterized adaptive foreground"

# ---- 3. macOS .icns via iconutil ------------------------------------------
ICONSET="$OUT/Paste.iconset"
mkdir -p "$ICONSET"
# iconutil expects this exact naming (point-size + @1x/@2x variants):
cp "$OUT/icon-16.png"   "$ICONSET/icon_16x16.png"
cp "$OUT/icon-32.png"   "$ICONSET/icon_16x16@2x.png"
cp "$OUT/icon-32.png"   "$ICONSET/icon_32x32.png"
cp "$OUT/icon-64.png"   "$ICONSET/icon_32x32@2x.png"
cp "$OUT/icon-128.png"  "$ICONSET/icon_128x128.png"
cp "$OUT/icon-256.png"  "$ICONSET/icon_128x128@2x.png"
cp "$OUT/icon-256.png"  "$ICONSET/icon_256x256.png"
cp "$OUT/icon-512.png"  "$ICONSET/icon_256x256@2x.png"
cp "$OUT/icon-512.png"  "$ICONSET/icon_512x512.png"
cp "$OUT/icon-1024.png" "$ICONSET/icon_512x512@2x.png"
if command -v iconutil >/dev/null; then
  iconutil -c icns "$ICONSET" -o "$OUT/Paste.icns"
  rm -rf "$ICONSET"
  echo "✓ built Paste.icns ($(du -h "$OUT/Paste.icns" | cut -f1))"
else
  echo "⚠ iconutil missing (non-macOS) — left iconset at $ICONSET"
fi

# ---- 4. Windows .ico via Pillow -------------------------------------------
# .ico is a multi-resolution container. Pillow's Image.save(format='ICO', sizes=…)
# takes a single source (we feed the 256 PNG) and embeds the requested subset.
python3 - <<'PY'
from PIL import Image
import os
out = os.path.join(os.environ["OUT"], "Paste.ico")
src = os.path.join(os.environ["OUT"], "icon-256.png")
img = Image.open(src).convert("RGBA")
img.save(out, format="ICO", sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)])
print(f"✓ built Paste.ico ({os.path.getsize(out)//1024} KB)")
PY

# ---- 5. Place files where each platform expects them ----------------------

# Expo (iOS + Android): mobile/pearpaste-expo/assets/images/
EXPO_ASSETS="$ROOT/mobile/pearpaste-expo/assets/images"
mkdir -p "$EXPO_ASSETS"
cp "$OUT/icon-1024.png"            "$EXPO_ASSETS/icon.png"
cp "$OUT/adaptive-icon-1024.png"   "$EXPO_ASSETS/adaptive-icon.png"
cp "$OUT/icon-180.png"             "$EXPO_ASSETS/favicon.png"
cp "$OUT/icon-256.png"             "$EXPO_ASSETS/splash-icon.png"
echo "✓ placed expo assets under $EXPO_ASSETS"

# Desktop / pear-electron: keep a stable assets/ at repo root the pear.json
# can reference, plus the multi-resolution outputs in icon-out/ for packaging.
DESKTOP_ASSETS="$ROOT/assets"
mkdir -p "$DESKTOP_ASSETS"
cp "$OUT/icon-1024.png" "$DESKTOP_ASSETS/icon.png"
cp "$OUT/icon-512.png"  "$DESKTOP_ASSETS/icon-512.png"
cp "$OUT/icon-256.png"  "$DESKTOP_ASSETS/icon-256.png"
# Tray icon (referenced by ui.app.tray() in ui/desktop/app.js)
cp "$OUT/icon-32.png"   "$DESKTOP_ASSETS/icon-32.png"
cp "$OUT/icon-64.png"   "$DESKTOP_ASSETS/icon-64.png"
cp "$OUT/Paste.icns"    "$DESKTOP_ASSETS/Paste.icns"
cp "$OUT/Paste.ico"     "$DESKTOP_ASSETS/Paste.ico"
echo "✓ placed desktop assets under $DESKTOP_ASSETS"

echo
echo "Done. Outputs:"
ls -lh "$OUT" "$DESKTOP_ASSETS" "$EXPO_ASSETS" 2>/dev/null | sed "s|$ROOT/|./|"
